# Generated by Django 3.2.10 on 2022-01-04 03:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.categoryservice', verbose_name='Категория услуги'),
            preserve_default=False,
        ),
    ]
