# Generated by Django 3.2.10 on 2022-01-15 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_service_category_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='content.categoryservice', verbose_name='Категория услуги'),
        ),
    ]
