# Generated by Django 3.2.10 on 2022-01-16 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20220116_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category_news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='content.categorynews', verbose_name='Категория новости'),
        ),
    ]
